### PR TITLE
Update format for trace

### PR DESCRIPTION
**Pull request by fflaten**
**PR updated to extend #53 which was merged first and added initial format files**

Updates format data with:
- Trace object shown in list-view as a "menu". Descriptions for each view
- Table-format for commandhit
- Right-aligned numeric values in table view
- String-representation of commandhit for use in dictionary-view

Also:
- Removed some references to use `Format-Table` which is no longer necessary
- Added vscode settings-file to use xml schemas for format ps1xml for easier editing

#### Trace object - interactive menu
```powershell
$trace

Top50Duration             : List top 50 lines based on duration
Top50HitCount             : List top 50 lines based on hit count
Top50SelfDuration         : List top 50 lines based on time consumed directly by the line
Top50FunctionDuration     : List top 50 functions based on duration
Top50FunctionHitCount     : List top 50 functions based on hit count
Top50FunctionSelfDuration : List top 50 functions based on time consumed directly by the function
AllLines                  : Show all lines processed by profiler trace
Events                    : Show raw trace-events returned from the profiler engine
TotalDuration             : 00:00:00.0000508
StopwatchDuration         : 00:00:00.0022765
```

#### Dictionary containing CommandHit
```powershell
$trace.Top50Duration[1].CommandHits

Key Value
--- -----
  5 Profiler.CommandHit: Line=17; Column=5; HitCount=1; SelfDuration=00:00:00.0015565; Text='$Values | foreach {…
 23 Profiler.CommandHit: Line=17; Column=23; HitCount=10000; SelfDuration=00:00:00.0423196; Text='{'

$trace.Top50Duration[1].CommandHits | Format-Table -Wrap

Key Value
--- -----
  5 Profiler.CommandHit: Line=17; Column=5; HitCount=1; SelfDuration=00:00:00.0015565; Text='$Values | foreach {
            $newValues += $_ + 10
        }'
 23 Profiler.CommandHit: Line=17; Column=23; HitCount=10000; SelfDuration=00:00:00.0423196; Text='{'
```

#### CommandHit view
```powershell
$trace.Top50Duration[0].CommandHits.Values

HitCount SelfDuration     Line Column Text
-------- ------------     ---- ------ ----
       1 00:00:00.0010832    1     82 {
       1 00:00:00.0043412    1     84 & .\demo-scripts\MyScript.ps1
       1 00:00:00.0000248    1    114 }
```

Related  #9

### CODE REVIEW

**Comment by fflaten** [comment]
Just to get some ideas going. Not sure how to format that dictionary better (if possible).

**Comment by nohwnd** [comment]
I think the dictionary is dictionary by accident, it should be just distinct commands I think. Will have to revisit that and also consider what it will do if we want to highlight commands that have big impact in line.

**Comment by nohwnd** [comment]
I forgot that his PR is here, do you want to merge the formatting for the trace and command hit type? :)

**Comment by nohwnd** [comment]
The name of the format file is also better than what I have :) So maybe just copy paste your styles into my file, and omit LineProfile, and then rename it.

**Comment by fflaten** [comment]
Merged and updated PR text. Ready for review.
Not sure about the `CommandHit.ToString()` format, but kept it as the dictionary is still there.

**Pull request merged**
